### ISSUE TITLE
Error in converting Ifc to wexbim file

### ISSUE THREAD

**Issue by Princepra** [xBimTeam/XbimExchange#47] opened 2019-09-23 10:13 UTC
while running the following code, got the error : 

**Exception thrown: 'System.IO.FileLoadException' in Xbim.Geometry.Engine.Interop.dll
The program '[20300] 12test.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.**

Here is my code:

using System;
using System.IO;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;
using Xbim.Geometry.Engine.Interop;

namespace _12test
{
    class Program
    {
        public static void Main(string[] args)
        {
            var fileName = "Ar.ifc";
            using (var model = IfcStore.Open(fileName))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var wexBimFilename = Path.ChangeExtension(fileName, "wexBIM");
                using (var wexBiMfile = File.Create(wexBimFilename))
                {
                    using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
                    {
                        model.SaveAsWexBim(wexBimBinaryWriter);
                        wexBimBinaryWriter.Close();
                    }
                    wexBiMfile.Close();
                }  
            }

            Console.WriteLine();   
        }
    }
}

**Comment by andyward** [comment] 2019-09-23 21:30
Duplicate of https://github.com/xBimTeam/XbimGeometry/issues/219 

This isn't an Exchange issue.

**Closed by andyward** 2019-09-23 21:30 UTC
