### ISSUE TITLE
Error in COBieBuilder.cs

### ISSUE THREAD

**Issue by ivanstef** [xBimTeam/XbimExchange#12] opened 2016-07-05 15:06 UTC
I receive the following error while running the CobieExport functionality:

           var path = OpenFile(fileId, FileFormat.Ifc);
            var credentials = ApplicationCredentials.XbimEditorCredentials;

            using (var ifcModel = IfcStore.Open(path, credentials, -1))
            {
                using (var cobie = new CobieModel())
                {
                    using (var transaction = cobie.BeginTransaction("Create COBie"))
                    {
                        var exchanger = new IfcToCoBieExpressExchanger(ifcModel, cobie);
                        exchanger.Convert();
                        transaction.Commit();
                    }

                    var cobieExportPath = HostingEnvironment.MapPath(
                        $"~/App_Data/Temp/{fileName}.xlsx");

                    string report;
                    cobie.ExportToTable(cobieExportPath, out report);

                    if (string.IsNullOrEmpty(report))
                        return cobieExportPath;

                    return report;
                }
            }

 The exception:
```
An exception of type 'System.MissingMethodException' occurred in Xbim.COBie.dll but was not handled in user code

Additional information: Method not found: 'System.Collections.IEnumerator NPOI.SS.UserModel.IRow.GetEnumerator()'.
```

on line 74 in COBieBuilder.cs

` COBieWorkbook wbook = deSerialiser.Deserialise();`

**Comment by ivanstef** [comment] 2016-07-12 09:07
After the latest updates the error is in XbimMappings.cs, Line 105

`An exception of type 'System.MissingMethodException' occurred in Xbim.Exchanger.dll but was not handled in user code`

`Additional information: Method not found: 'Boolean Xbim.CobieExpress.CobieRole.op_Equality(Xbim.CobieExpress.CobieRole, Xbim.CobieExpress.CobieRole)'.`

**Comment by SteveLockley** [comment] 2016-09-28 15:31
This was caused by duplicate versions of NPOI being installed by the Nuget packager, it is now fixed in the develop branch

**Closed by SteveLockley** 2016-09-28 15:31 UTC
